services:
  db2:
    image: ibmcom/db2
    platform: linux/amd64
    container_name: db2
    privileged: true
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=db2inst1_password
      - SAMPLEDB=true
    volumes:
      - db2:/database
    ports:
      - "50000:50000"
    command: >
      bash -c "
        su - db2inst1 -c '. /database/config/db2inst1/sqllib/db2profile && 
        db2 connect to SAMPLE &&
        tail -f /dev/null'
      "
    healthcheck: 
      test: ["CMD-SHELL", "su - db2inst1 -c '. /database/config/db2inst1/sqllib/db2profile && db2 connect to SAMPLE && db2 list active databases >/dev/null' || exit 1"] 
      interval: 30s 
      timeout: 10s 
      retries: 10 
      start_period: 120s

  splunk:
    image: splunk/splunk:latest
    platform: linux/amd64
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
      - SPLUNK_PASSWORD=YourPassword123
    volumes:
      - db2:/database:ro
      - ./splunk_inputs:/opt/splunk/etc/system/local
    ports:
      - "8000:8000"
      - "9997:9997"
    
volumes:
  db2:
